### ISSUE TITLE
RN no visible @interface for 'RCTTextField' declares the selector 'textField' 

### ISSUE THREAD

**Issue by evasyuk** [react-native-text-input-mask/react-native-text-input-mask#25]
MacBook-Air-jennyzhmenny:taxi jv$ react-native --version
react-native-cli: 2.0.1
react-native: 0.48.4

Console output:

> /Users/jv/code/taxi/node_modules/react-native-text-input-mask/ios/RNTextInputMask/RNTextInputMask/RNTextInputMask.m:40:46: error: no visible @interface for 'RCTTextField' declares the selector 'textField'
>             RCTUITextField *textView = [view textField];
>                                         ~~~~ ^~~~~~~~~
> 1 error generated.
> 
> 
> 
> ** BUILD FAILED **
> 
> 
> 
> The following build commands failed:
> 	CompileC /Users/jv/code/taxi/ios/build/Build/Intermediates.noindex/RNTextInputMask.build/Debug-iphonesimulator/RNTextInputMask.build/Objects-normal/x86_64/RNTextInputMask.o RNTextInputMask/RNTextInputMask.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
> (1 failure)

Simple rollback to 0.47.2 did not make a trick(upraises problem with dependencies mismatch)

**Comment by deehuey** [comment]
Yup! 👍 Getting this as well.

**Comment by kamaljit-sharma** [comment]
+1

**Comment by bintoll** [comment]
+1, works good on android, but can not build on ios(

**Comment by leoneparise** [comment]
For me it's working on RN 0.52.2

**Comment by chitra591** [comment]
Hi @evasyuk !
Even I get this error while building, but only on iOS

Were you guys able to find a solution?

My react-native version is 0.49.3 and react-native-text-input-mask version is 0.3.2

Thanks!

**Comment by bintoll** [comment]
Not really, after updating react native and updating this lib everything works good. I do not think that it is like real solution for this but if you finally would not be able to resolve it anyway you can always make an update)

**Comment by chitra591** [comment]
Thank you so much @bintoll
